%{?!ros_distro:%global ros_distro lyrical}
%global pkg_name aruco
%global normalized_pkg_name %{lua:return (string.gsub(rpm.expand('%{pkg_name}'), '_', '-'))}

Name:           ros-lyrical-aruco
Version:        5.0.5
Release:        3%{?dist}
Summary:        ROS %{pkg_name} package

License:        MIT
URL:            http://www.uco.es/investiga/grupos/ava/node/26
Source0:        %{name}-%{version}.tar.gz

BuildRequires:  bloom-rpm-macros
BuildRequires:  cmake

%{?bloom_package}

%description
The ARUCO Library has been developed by the Ava group of the Univeristy of
Cordoba(Spain). It provides real-time marker based 3D pose estimation using AR
markers.


%package devel
Release:        %{release}%{?release_suffix}
Summary:        %{summary}
Provides:       %{name} = %{version}-%{release}
Provides:       %{name}%{?_isa} = %{version}-%{release}
Requires:       %{name}-runtime%{?_isa} = %{version}-%{release}

%description devel
The ARUCO Library has been developed by the Ava group of the Univeristy of
Cordoba(Spain). It provides real-time marker based 3D pose estimation using AR
markers.


%package runtime
Release:        %{release}
Summary:        %{summary}

%description runtime
The ARUCO Library has been developed by the Ava group of the Univeristy of
Cordoba(Spain). It provides real-time marker based 3D pose estimation using AR
markers.


%prep
%autosetup -p1


%generate_buildrequires
%bloom_buildrequires


%build
%cmake \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="%{bloom_prefix}" \
    -DAMENT_PREFIX_PATH="%{bloom_prefix}" \
    -DCMAKE_PREFIX_PATH="%{bloom_prefix}" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif

%cmake3_build


%install
%cmake_install


%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C %{__cmake_builddir} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
CTEST_OUTPUT_ON_FAILURE=1 \
    %cmake_build $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif


%files devel
%dir %{bloom_prefix}
%ghost %{bloom_prefix}/share/%{pkg_name}/package.xml


%files runtime
%{bloom_prefix}


%changelog
* Wed Apr 29 2026 Sai Kishor Kothakota <sai.kishor@pal-robotics.com> - 5.0.5-3
- Autogenerated by Bloom

* Tue Apr 28 2026 Sai Kishor Kothakota <sai.kishor@pal-robotics.com> - 5.0.5-2
- Autogenerated by Bloom

* Tue Apr 21 2026 Sai Kishor Kothakota <sai.kishor@pal-robotics.com> - 5.0.5-1
- Autogenerated by Bloom
